### ISSUE TITLE
Read only mode is not displayed in all tabs and not in all cases.

### ISSUE THREAD

**Issue by DivineThreepwood** [openbase/bco.registry.editor#28]
1. start bco-registry (normal)
2. start bco-registry-editor and wait until connected
3. shutdown bco-registry
4. start bco-registry (read-only)
5. wait until bco-registry-editor as established the connection again

After this the registry-editor does not display "read only mode" in all tabs.

**Comment by pLeminoq** [comment]
I think there was an error that the editor did not check for the read only mode on every data update. This should be fixed with commit eae24a8e179add57cb2b03d17601b88434c4909d.
But the read only mode is still not displayed in every tab. But the error seems to be in the registry. The read only mode does not seem to be published correctly for all registries especially the unit registry.

**Comment by pLeminoq** [comment]
After the referenced issue had been fixed this works now.
