### ISSUE TITLE
Unit groups fold on apply change

### ISSUE THREAD

**Issue by THuppke** [openbase/bco.registry.editor#35]
Other than in the UnitConfig section, the Unit Groups will fold once Apply is clicked.
I think the preffered handling is the one of the UnitConfig section, where the config remains unfolded as it was.

**Comment by THuppke** [comment]
Anyway, why is that not solved in a generic fashion? :/

**Comment by pLeminoq** [comment]
Should be fixed by commit 0f86110a6239edaab8e26251580ade81ad5c567b.
It was implemented in a generic fashion but the implementation had a bug.
The implementation only dealt with entries which were grouped correctly. This is why it worked for UnitConfigs because they are grouped by location and unitType.
